### ISSUE TITLE
%sveltekit.nonce% not being replaced

### ISSUE THREAD

**Issue by EdwardLemayDev** [svecosystem/mode-watcher#47]
Good day,

I don't know if it was something that was noticed, but it seems like the nonce isn't being replaced when added dynamically with <svelte:head>. 
I was taking inspiration on your project for a personal alternative that would change a data attribute instead, and initially thought it was a mistake on my end for the nonce.
After trying mode-watcher, I found out that it was behaving the same way as my attempt.
If that's normal could somebody explain, I don't see it replaced even when building the app and it got me confused.

**Comment by huntabyte** [comment]
I'm not exactly sure why this isn't being replaced. We're only using this as a workaround due to an issue with the eslint plugin for svelte. I'd raise an issue with kit about the nonce.

**Comment by ollema** [comment]
I wonder if this ever worked? or maybe it only works in app.html

**Comment by sksar** [comment]
Maybe something to do with this https://github.com/sveltejs/kit/issues/7945 and this https://github.com/sveltejs/kit/issues/8427

**Comment by ollema** [comment]
I actually think there is more we can do here on this issue.

I believe, based on:

1. in the [docs](https://github.com/sveltejs/kit/blob/4ae1cd152a60a22044ab3b8aa5572a2b79864583/packages/kit/src/core/sync/write_server.js#L53), they mention:
> To add a nonce for scripts and links manually included in `src/app.html`, you may use the placeholder `%sveltekit.nonce%` (for example `<script nonce="%sveltekit.nonce%">`).

notice how only `src/app.html` is mentioned here!

2. in the [source code](
https://github.com/sveltejs/kit/blob/4ae1cd152a60a22044ab3b8aa5572a2b79864583/packages/kit/src/core/sync/write_server.js#L53), notice how only the app template does the replacement for `%sveltekit.nonce%`:
```ts
	templates: {
		app: ({ head, body, assets, nonce, env }) => ${s(template)
			.replace('%sveltekit.head%', '" + head + "')
			.replace('%sveltekit.body%', '" + body + "')
			.replace(/%sveltekit\.assets%/g, '" + assets + "')
			.replace(/%sveltekit\.nonce%/g, '" + nonce + "')
			.replace(
				/%sveltekit\.env\.([^%]+)%/g,
				(_match, capture) => `" + (env[${s(capture)}] ?? "") + "`
			)},
		error: ({ status, message }) => ${s(error_page)
			.replace(/%sveltekit\.status%/g, '" + status + "')
			.replace(/%sveltekit\.error\.message%/g, '" + message + "')}
	},
```

I tried to search the kit codebase for other replacements/usages of `%sveltekit.nonce%` or even just `nonce` but could not find any. please let me know if I missed anything!

---

my conclusion is that `%sveltekit.nonce%` only works in `src/app.html`. 

therefore, I think we should:

- remove `%sveltekit.nonce%` from `mode-watcher` since it just leads to confusion. both in this issue and potentially in issues like https://github.com/svecosystem/mode-watcher/issues/39#issuecomment-1825960152 as well
- include instructions for you could configure `mode-watcher` to work with more restrictive CSP settings. in practice I think this means manually copying and pasting the FOUC prevention snippet to your `src/app.html` along with a `%sveltekit.nonce%` nonce property (that actually does get replaced!). would need to think about how to handle minimization here or even if `mode-watcher` should publish the snippet to some CDN like jsdelivr, not sure here.


---

thoughts? @huntabyte

**Comment by ollema** [comment]
aha, or is the idea that we use `<svelte:head>` to inject our FOUC prevention snippet into `%sveltekit.head%` and therefore it should indeed be present before the `%sveltekit.nonce%` replacement happens?

if so, that does sound like a bug in kit. sorry for the false alarm 🤦

**Comment by ollema** [comment]
actually, scratch that last comment. I learned in a conversation on discord that the conclusion I drew earlier was correct. it has never worked and it will never work to have `%sveltekit.nonce%` in `<svelte:head>` as that is not safe.

so we are back to: 
> - remove `%sveltekit.nonce%` from `mode-watcher` since it just leads to confusion. both in this issue and potentially in issues like https://github.com/svecosystem/mode-watcher/issues/39#issuecomment-1825960152 as well
> - include instructions for you could configure `mode-watcher` to work with more restrictive CSP settings. in practice I think this means manually copying and pasting the FOUC prevention snippet to your `src/app.html` along with a `%sveltekit.nonce%` nonce property (that actually does get replaced!). would need to think about how to handle minimization here or even if mode-watcher should publish the snippet to some CDN like jsdelivr, not sure here.

we could also look into [hashes](https://content-security-policy.com/hash/) but that also complicates things when it comes to minimisation.

overall, personally I think it makes to:

- have an "easy mode" for users who do not configure CSP. then `mode-watcher` just requires two lines of code in `+layout.svelte`
- have an "advanced mode" for users who do configure CSP. then we ask them to add the FOUC prevention snippet themselves to `src/app.html`. how we do that is up for debate:
  - ask them to copy and paste a `<script nonce="%sveltekit.nonce%">...` snippet
  - ask them to include a `<script src="..." integrity="sha256-xyz...">` from a CDN and also configure [CSP directives](https://kit.svelte.dev/docs/configuration#csp) in kit to include `sha256-xyz..."
  
for the advanced mode, I think I prefer the first option which leads to more lines of code in `src/app.html` but no extra configuration of kit

**Comment by ollema** [comment]
>  Part of me doesn't want to _ignore_ the fact that it doesn't get replaced, but at the same time **I want adding mode-watcher to projects to remain as simple as possible.**

yeah I think that sounds great - I do think that if we still want to keep it simple we should just remove it since right now it does nothing but instead it adds confusion

> I think I'm leaning towards your approach of the advanced/vs basic usage, but will further investigate this weekend.

👍

**Comment by vyconm** [comment]
hey guys, just ran into this in a production app.

Would you mind sharing a workaround until this gets fixed? Alternatively I could just implement different dark mode switching, but this package is pretty neat.

thank you!
